//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPNet.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAPNet.Tests.Xml", typeof(Xml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding = &quot;UTF-8&quot;?&gt;
        ///&lt;alert xmlns = &quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;TRI13970876.2&lt;/identifier&gt; 
        ///  &lt;sender&gt;trinet@caltech.edu&lt;/sender&gt; 
        ///  &lt;sent&gt;2003-06-11T20:56:00-07:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt; 
        ///  &lt;msgType&gt;Update&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt;
        ///  &lt;references&gt;trinet@caltech.edu,TRI13970876.1,2003-06-11T20:30:00-07:00&lt;/references&gt;
        ///  &lt;info&gt;
        ///    &lt;category&gt;Geo&lt;/category&gt;
        ///    &lt;event&gt;Earthquake&lt;/event&gt;   
        ///    &lt;urgency&gt;Past&lt;/urgency&gt;   
        ///    &lt;severit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string circleXml {
            get {
                return ResourceManager.GetString("circleXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;alert xmlns=&quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;43b080713727&lt;/identifier&gt;
        ///  &lt;sender&gt;hsas@dhs.gov&lt;/sender&gt;
        ///  &lt;sent&gt;2003-04-02T14:39:01-05:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt;
        ///  &lt;msgType&gt;Alert&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt;
        ///  &lt;source&gt;source&lt;/source&gt;
        ///  &lt;restriction&gt;restriction&lt;/restriction&gt;
        ///  &lt;addresses&gt;addresses&lt;/addresses&gt;
        ///  &lt;code&gt;code&lt;/code&gt;
        ///  &lt;note&gt;note&lt;/note&gt;
        ///  &lt;references&gt;references&lt;/references&gt;
        ///  &lt;incidents&gt;incidents&lt;/incidents&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipleAlertXml {
            get {
                return ResourceManager.GetString("MultipleAlertXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;&quot;1.0&quot;&quot; encoding = &quot;&quot;UTF-8&quot;&quot;?&gt;
        ///&lt;alert xmlns = &quot;&quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&quot;&gt;
        ///  &lt;identifier&gt;TRI13970876.2&lt;/identifier&gt; 
        ///  &lt;sender&gt;trinet@caltech.edu&lt;/sender&gt; 
        ///  &lt;sent&gt;2003-06-11T20:56:00-07:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt; 
        ///  &lt;msgType&gt;Update&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt;
        ///  &lt;references&gt;trinet@caltech.edu,TRI13970876.1,2003-06-11T20:30:00-07:00&lt;/references&gt;
        ///  &lt;info&gt;
        ///    &lt;category&gt;Geo&lt;/category&gt;
        ///    &lt;event&gt;Earthquake&lt;/event&gt;   
        ///    &lt;urgency&gt;Past&lt;/urgency&gt;   
        ///    &lt;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipleCircleXml {
            get {
                return ResourceManager.GetString("MultipleCircleXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;alert xmlns=&quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;43b080713727&lt;/identifier&gt;
        ///  &lt;sender&gt;hsas@dhs.gov&lt;/sender&gt;
        ///  &lt;sent&gt;2003-04-02T14:39:01-05:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt;
        ///  &lt;msgType&gt;Alert&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt;
        ///  &lt;info&gt;
        ///    &lt;category&gt;Security&lt;/category&gt;
        ///    &lt;category&gt;Safety&lt;/category&gt;
        ///    &lt;event&gt;Homeland Security Advisory System Update&lt;/event&gt;
        ///    &lt;urgency&gt;Immediate&lt;/urgency&gt;
        ///    &lt;severity&gt;Severe&lt;/severity&gt;
        ///    &lt;certainty&gt;V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipleParameterTestXml {
            get {
                return ResourceManager.GetString("MultipleParameterTestXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding = &quot;UTF-8&quot;?&gt;
        ///&lt;alerts&gt;
        ///&lt;alert xmlns = &quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;KSTO1055887203&lt;/identifier&gt; 
        ///  &lt;sender&gt;KSTO@NWS.NOAA.GOV&lt;/sender&gt; 
        ///  &lt;sent&gt;2003-06-17T14:57:00-07:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt; 
        ///  &lt;msgType&gt;Alert&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt; 
        ///  &lt;info&gt;
        ///    &lt;category&gt;Met&lt;/category&gt;   
        ///    &lt;event&gt;SEVERE THUNDERSTORM&lt;/event&gt;
        ///    &lt;responseType&gt;Shelter&lt;/responseType&gt; 
        ///    &lt;urgency&gt;Immediate&lt;/urgency&gt;   
        ///    &lt;severity&gt;Severe&lt;/severity&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultipleThunderstorm12Xml {
            get {
                return ResourceManager.GetString("MultipleThunderstorm12Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;alert xmlns=&quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;43b080713727&lt;/identifier&gt;
        ///  &lt;sender&gt;hsas@dhs.gov&lt;/sender&gt;
        ///  &lt;sent&gt;2003-04-02T14:39:01-05:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt;
        ///  &lt;msgType&gt;Alert&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt;
        ///  &lt;info&gt;
        ///    &lt;category&gt;Security&lt;/category&gt;
        ///    &lt;event&gt;Homeland Security Advisory System Update&lt;/event&gt;
        ///    &lt;urgency&gt;Immediate&lt;/urgency&gt;
        ///    &lt;severity&gt;Severe&lt;/severity&gt;
        ///    &lt;certainty&gt;Likely&lt;/certainty&gt;
        ///    &lt;senderNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrangeAlertXml {
            get {
                return ResourceManager.GetString("OrangeAlertXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding = &quot;UTF-8&quot;?&gt;
        ///&lt;alert xmlns = &quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;KSTO1055887203&lt;/identifier&gt; 
        ///  &lt;sender&gt;KSTO@NWS.NOAA.GOV&lt;/sender&gt; 
        ///  &lt;sent&gt;2003-06-17T14:57:00-07:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt; 
        ///  &lt;msgType&gt;Alert&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt; 
        ///  &lt;info&gt;
        ///    &lt;category&gt;Met&lt;/category&gt;   
        ///    &lt;event&gt;SEVERE THUNDERSTORM&lt;/event&gt;
        ///    &lt;responseType&gt;Shelter&lt;/responseType&gt; 
        ///    &lt;urgency&gt;Immediate&lt;/urgency&gt;   
        ///    &lt;severity&gt;Severe&lt;/severity&gt;   
        ///    &lt;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Thunderstorm12AllDatesXml {
            get {
                return ResourceManager.GetString("Thunderstorm12AllDatesXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding = &quot;UTF-8&quot;?&gt;
        ///&lt;alert xmlns = &quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;KSTO1055887203&lt;/identifier&gt; 
        ///  &lt;sender&gt;KSTO@NWS.NOAA.GOV&lt;/sender&gt; 
        ///  &lt;sent&gt;2003-06-17T14:57:00-07:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt; 
        ///  &lt;msgType&gt;Alert&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt; 
        ///  &lt;info&gt;
        ///    &lt;category&gt;Met&lt;/category&gt;   
        ///    &lt;event&gt;SEVERE THUNDERSTORM&lt;/event&gt;
        ///    &lt;responseType&gt;Shelter&lt;/responseType&gt; 
        ///    &lt;urgency&gt;Immediate&lt;/urgency&gt;   
        ///    &lt;severity&gt;Severe&lt;/severity&gt;   
        ///    &lt;c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Thunderstorm12Xml {
            get {
                return ResourceManager.GetString("Thunderstorm12Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version = &quot;1.0&quot; encoding = &quot;UTF-8&quot;?&gt;
        ///&lt;alert xmlns = &quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;KSTO1055887203&lt;/identifier&gt; 
        ///  &lt;sender&gt;KSTO@NWS.NOAA.GOV&lt;/sender&gt; 
        ///  &lt;sent&gt;2003-06-17T14:57:00-07:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt;
        ///  &lt;msgType&gt;Update&lt;/msgType&gt;
        ///  &lt;scope&gt;Restricted&lt;/scope&gt;
        ///  &lt;restriction&gt;Only people with glasses should receive this update.&lt;/restriction&gt;
        ///  &lt;info&gt;
        ///    &lt;category&gt;Met&lt;/category&gt;
        ///    &lt;event&gt;SEVERE THUNDERSTORM&lt;/event&gt;
        ///    &lt;responseType&gt;Shelter&lt;/responseType [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThunderstormUpdate12Xml {
            get {
                return ResourceManager.GetString("ThunderstormUpdate12Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;alert xmlns=&quot;urn:oasis:names:tc:emergency:cap:1.2&quot;&gt;
        ///  &lt;identifier&gt;43b080713727&lt;/identifier&gt;
        ///  &lt;sender&gt;hsas@dhs.gov&lt;/sender&gt;
        ///  &lt;sent&gt;2003-04-02T14:39:01-05:00&lt;/sent&gt;
        ///  &lt;status&gt;Actual&lt;/status&gt;
        ///  &lt;msgType&gt;Alert&lt;/msgType&gt;
        ///  &lt;scope&gt;Public&lt;/scope&gt;
        ///  &lt;info&gt;
        ///    &lt;category&gt;Security&lt;/category&gt;
        ///    &lt;event&gt;Homeland Security Advisory System Update&lt;/event&gt;
        ///    &lt;urgency&gt;Immediate&lt;/urgency&gt;
        ///    &lt;severity&gt;Severe&lt;/severity&gt;
        ///    &lt;certainty&gt;Very Likely&lt;/certainty&gt;
        ///    &lt;send [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VeryLikelyOrangeAlertXml {
            get {
                return ResourceManager.GetString("VeryLikelyOrangeAlertXml", resourceCulture);
            }
        }
    }
}
